# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joyce Blog title
SEOTitle: Joyce'Blog
header-img: img/post-bg-desk.jpg
email: joycefangmm@gmail.com
description: "description: my first step!"
  # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_repo: "https://github.com/JoyceFangmm/JoyceFangmm.github.io.git"

# Build settings
markdown: kramdown
# theme: minima      #default jekyll theme
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  # - Gemfile
  # - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
# service-worker: true

# Featured Tags
featured-tags: false                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-JoyceFang-gentle.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# SNS settings
RSS: true
twitter_username: joycefang
github_username:  joycefangmm


# Friends
friends: [
    {
        title: "Google",
        href: "http://www.google.com"
    },{
        title: "Bing",
        href: "http://www.bing.com"
    },{
        title: "Apple",
        href: "https://www.apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]